package:
  name: populate35
  version: "0.0.0"

requirements:
  build:
    - anaconda 2.5.0 np110py35_0
    - bokeh
    - numba
    - dask
    - odo
    - blaze
    - holoviews
  run:
    - anaconda 2.5.0 np110py35_0
    - bokeh
    - numba
    - dask
    - odo
    - blaze
    - holoviews
