# Tell appveyor to not use msbuild
build: false

platform:
  - x64

init:
  - "ECHO %PYTHON%"
  - ps: Start-FileDownload 'http://repo.continuum.io/miniconda/Miniconda2-latest-Windows-x86_64.exe' C:\Miniconda.exe; echo "Done"
  - cmd: C:\Miniconda.exe /S /D=C:\Miniconda
  - ps: ls C:\Miniconda/Scripts
  - C:\Miniconda\Scripts\conda config --set always_yes yes
  - C:\Miniconda\Scripts\conda install -c conda pytest requests conda-env conda-build ndg-httpsclient --quiet

install:
  - C:\Miniconda\python.exe setup.py install
  - C:\Miniconda\Scripts\conda info -a
  - C:\Miniconda\Scripts\conda list

test_script:
  - C:\Miniconda\Scripts\py.test -vvv
  - C:\Miniconda\Scripts\conda --help
  - IF %PYTHON%==2.7 IF DEFINED PYCOSAT C:\Miniconda\Scripts\conda install -f menuinst ipython-notebook & echo "Finished menuinst test"
