name: usb-cuba-linux-py27
dependencies:
- anaconda=2.5
- python=2.7
- anaconda-build
- bcolz
- biopython
- blaze
- bokeh
- bz2file
- chardet
- cmake
- conda-api
- coverage
- csvkit
- cvxopt
- dask
- dbf
- django
- ecdsa
- ephem
- expat
- feedparser
- flake8
- future
- gensim
- git
- graphviz
- gunicorn
- holoviews
- iso8601
- jmespath
- joblib
- libnetcdf
- line_profiler
- lz4
- markdown
- markdown2
- mathjax
- memory_profiler
- mpi4py
- mpich2
- mpmath
- msgpack-python
- mysql-python
- nano
- ncurses
- netcdf4
- numba
- numpydoc
- odo
- openmpi
- orange
- pandas-datareader
- pandasql
- pcre
- posix-ipc
- progressbar
- proj4
- protobuf
- psycopg2
- pylint
- pymc
- pymongo
- pymysql
- pyobdc
- pyopengl
- pyopengl-accelerate
- pyproj
- pysal
- pysam
- pyserial
- python-ntlm
- r-essentials
- routes
- runipy
- sas7bdat
- scikit-bio
- scrapy
- seaborn
- semantic_version
- sh
- shapely
- snakebite
- snakeviz
- sqlparse
- swig
- theano
- translationstring
- twisted
- unidecode
- unixodbc
- uuid
- websocket
- webtest
- whoosh
- workerpool
- wrapt
- xarray
- xlutils
- yt
    
