name: usb-cuba-linux-py35
dependencies:
- anaconda=2.5
- python=3.5
- anaconda-build
- bcolz
- biopython
- blaze
- bokeh
- bz2file
- chardet
- cmake
- conda-api
- coverage
# - csvkit # conflict with package anaconda 2.5
- cvxopt
- dask
- dbf
- django
- ecdsa
- ephem
- expat
- feedparser
- flake8
- future
- gensim
- git
- graphviz
- gunicorn
- holoviews
- iso8601
- jmespath
- joblib
# - libnetcdf # conflict with package anaconda 2.5
- line_profiler
- lz4
- markdown
- markdown2
- mathjax
- memory_profiler
- mpi4py
- mpich2
- mpmath
- msgpack-python
# - mysql-python # conflict with package python 3.5
- nano
- ncurses
# - netcdf4 # conflict with package anaconda 2.5
- numba
- numpydoc
- odo
# - openmpi # no package found in linux-64 channels
# - orange # conflict with package python 3.5
- pandas-datareader
# - pandasql # conflict with package python 3.5
- pcre
# - posix-ipc # no package found in linux-64 channels
# - progressbar # conflict with package python 3.5
- proj4
# - protobuf # conflict with package python 3.5
# - psycopg2 # conflict with package anaconda 2.5
- pylint
- pymc
- pymongo
- pymysql
# - pyobdc # no package found in linux-64 channels
- pyopengl
- pyopengl-accelerate
- pyproj
# - pysal # conflict with package python 3.5
# - pysam # conflict with package python 3.5
- pyserial
# - python-ntlm # conflict with package python 3.5
# - r-essentials # no package found in linux-64 channels
- routes
- runipy
- sas7bdat
- scikit-bio
# - scrapy # conflict with package python 3.5
- seaborn
- semantic_version
- sh
- shapely
# - snakebite # conflict with package python 3.5
- snakeviz
- sqlparse
- swig
- theano
- translationstring
- twisted
- unidecode
- unixodbc
# - uuid # conflict with package python 3.5
# - websocket # conflict with package anaconda 2.5
# - webtest # conflict with both anaconda 2.5 and python 3.5
- whoosh
- workerpool
- wrapt
- xarray
# - xlutils # conflict with package python 3.5
- yt
