package:
  name: repo-populate
  version: "0.0.0"

requirements:
  build:
    - python
    - anaconda-client

  # build:
  #   - anaconda 2.5.0 np110py27_0
  #   - bokeh
  #   - numba
  #   - dask
  #   - odo
  #   - blaze
  #   - holoviews
  # run:
  #   - anaconda 2.5.0 np110py27_0
  #   - bokeh
  #   - numba
  #   - dask
  #   - odo
  #   - blaze
  #   - holoviews
